### PR TITLE
Fix networking error

### PR DESCRIPTION
**Pull request by devotox**

### CODE REVIEW

**Comment by devotox** [comment]
@ar90n ping!

**Comment by ar90n** [comment]
Hi @devotox 
Thank for your PR. But I cannot understand it correctly. Why should we remove then clause ? Please tell me the reason .

**Comment by devotox** [comment]
It seems if you use noStart on offline and start s3 like this

```
npx sls s3 start \
	--host ${HOST} \
	--port ${S3_PORT} \
	--directory /tmp \
	--location ../../.webpack/${SERVICE}/service &

npx sls offline start \
	--host ${HOST} \
	--stage ${STAGE} \
	--region ${REGION} \
	--port ${LAMBDA_PORT} \
	--noStart true
```

That line above actually shuts the server down and you are not able to actually send anything to the s3rver

**Comment by ar90n** [comment]
Hi @devotox 
Thanks for your description. But I think it's odd. Because it works correctly in my environment. Also if this PR is merged, hook integration with serverless-offline won't work. So I cannot merge this PR.

**Pull request closed without merging**
