### PR TITLE
Enable integration with serverless-webpack and serverless-offline.

### PR DESCRIPTION
**Pull request by obearn**
Enable integration with serverless-webpack and serverless-offline by updating options with serverless-webpack entry for serverless-offline when webpack builds the lambda

### CODE REVIEW

**Comment by ar90n** [comment]
Hi @obearn 
Thanks for your PR.
But I think the current implementation of serverless-s3-local has capability to cooperate with serverless-webpack and serverless-offline.
In the _setOptions function, there are some codes which are similar to yours.

**Comment by ar90n** [comment]
If you don't mind, please let me know your environment which doesn't work.

**Comment by obearn** [comment]
Hi,

Ok sorry I think I didn't have the last version, I just updated and it
works. I can see the _setOptions is exactly what  I needed.

Thank you.

2018-06-28 3:17 GMT+02:00 Masahiro Wada <notifications@github.com>:

**Comment by ar90n** [comment]
Hi @obearn
I got it. It sounds good !!
Thanks for using serverless-s3-local.

**Pull request closed without merging**
