### PR TITLE
create + remove commands

### PR DESCRIPTION
**Pull request by mvayngrib**
apologies in advance, this kind of got away from me. You can check the individual commits, which I would ordinarily make individual PRs for, but basically:
1. error propagation from failures
2. add 'create' command
3. add 'remove' command - this one might be controversial, as i'm using the aws-cli via shelljs, but otherwise this repo would need to have and maintain it's own implementation of list + clear + delete a bucket.

### CODE REVIEW

**Comment by ar90n** [comment]
Hi @mvayngrib 
Thanks for your PR.
I read your PR but I cannot make sense the purpose of this PR clearly.
I guess that you want to create and remove buckets by not aws-cli but serverless command.
My guess is the following.
```bash
$ serverless offline start
$ serverless s3 remove
```
Is it correct ?

**Comment by mvayngrib** [comment]
@ar90n exactly. And if this makes sense to you, I would also want to add a flag to skip creating buckets on start. `sls offline start` gets slowed down by all the various plugins creating stuff that only needs to be created once.

**Comment by ar90n** [comment]
I understood what this PR wants to do. But I'm afraid that I think they are not suitable for  the tasks of serverless-s3-local. For these case, I think we should use aws-cli tools or other tools.

But I agree with your suggestion which is to support skip creating buckets.
I will start to implement these functions soon. Please wait for it.

**Comment by mvayngrib** [comment]
@ar90n thanks for responding. Your decision of course, but I'm not sure I understood for which part we should use aws-cli instead. Instead of `sls s3 create` and `sls s3 remove`?

**Comment by ar90n** [comment]
@mvayngrib  Sorry for my late reply. In my opinion, I think the following commands will fulfill your needs.
```
$ aws --endpoint http://localhost:8000 s3api create-bucket --bucket foo
$ aws --endpoint http://localhost:8000 s3api delete-bucket --bucket foo
```
Please check them.

**Comment by mvayngrib** [comment]
@ar90n right, I know I can use aws-cli to create buckets individually. The convenience of having it in the plugin is that it creates all the buckets defined in serverless.yml. Isn't that the point of the plugin? I just wanted to be able to run `sls s3 create` one time during initialization, and then `sls offline start` _many_ times on without taking a performance penalty. Maybe I wasn't clear :)

**Comment by ar90n** [comment]
@mvayngrib Thanks for your comment. I found that my recognition was wrong. I agree with you. The aim of this PR is the scope of this plugin. I want to merge this PR but I have questions.  

1. shelljs is really neccesary ? 
1. There are no ways to ahchieve this function by AWS.S3 instance like createBuckets ?

I really appreciate for your sincere response regardless of my poor english.

**Comment by mvayngrib** [comment]
@ar90n maybe instead of shelljs, we can use https://github.com/sabrehagen/empty-aws-bucket, what do you think? removing buckets is a little tricky if they have versioning enabled

**Comment by ar90n** [comment]
@mvayngrib I understand that removing bucket is tricky against expectations.So I think using shelljs is the best solution.I'm going to merge this PR and publish it.Thanks for your great contribution !

**Comment by mvayngrib** [comment]
@ar90n thanks :)

**Comment by ar90n** [comment]
@mvayngrib  I published new version as v0.2.11. Please install it via npm.

**Comment by mvayngrib** [comment]
@ar90n awesome, thanks!

**Pull request merged**
