### PR TITLE
Adding support for Resources in Additional Stacks (plugin)

### PR DESCRIPTION
**Pull request by gevorggalstyan**

### CODE REVIEW

**Comment by ar90n** [comment]
HI gevorggalstyan.

Thanks for you PR.
It is nice and provides us great benefits of improving feature and making codes mode beautiful.
But I think lodash  is not necessary for this case.
Because it is only used for simple task and I want to keep this project simple.
So please modify and omit the dependency of lodash ?

**Comment by gevorggalstyan** [comment]
Hi @ar90n,

Thanks for your comment.
Could not disagree with you. Remove the loads dependency. 

VR,
Gevorg

**Comment by ar90n** [comment]
Thanks for your great effort.
I merged this PR and released v0.2.7.
Please install it via npm !

**Comment by gevorggalstyan** [comment]
Awesome! Thanks.

**Pull request merged**
